config/routes.rb
Rails.application.routes.draw do
  root to: "pets#index"
  resources :pets, except: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name,presence: true
  SPECIES = ["Cat", "Dog", "Cameleon", "Koala", "Kangoroo", "Crabe"]
  validates :species, presence: true, inclusion: { in: SPECIES } 

  after_validation :today_is_the_day

  private

  def today_is_the_day
    return if self.found_on.present?
    self.found_on = Time.zone.now
  end

  # def self.species
  #   SPECIES
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to root_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder:"ex: kitty" %>
  
  <%= f.label :address %>
  <%= f.text_field :address %>
  
  <%= f.label :species %>
  <%= f.select :species, Pet::SPECIES  %>
  
  <%= f.label :found_on %>
  <%= f.datetime_field :found_on %>

  <%= f.submit "click!" %>
<% end %>

app/views/pets/edit.html.erb
<%= render("form", { pet: @pet, toto: "taat" }) %>

app/views/pets/index.html.erb
<h1>Tous les pets</h1>

<% @pets.each do |pet| %>
  <%= link_to pet_path(pet) do %>
      <p><%= pet.name %>, <%= pet.species %></p>
    <% end %>
<% end %>

app/views/pets/new.html.erb
<%= render("form", pet: @pet) %>

app/views/pets/show.html.erb
<h1>Pets#show</h1>
<p>Find me in app/views/pets/show.html.erb</p>

<%= @pet.name %>
<%= @pet.species %>
<%= @pet.address %>
<p><%= @pet.found_on.strftime("%m/%d/%Y à %H:%M") %></p>

<%= link_to "home", root_path %>
<%= link_to "edit", edit_pet_path(@pet) %>
<%= link_to "delete", pet_path(@pet), method: :delete, data: { confirm: { "are you sure ?"}} %>